package org.rtkcollector.app.recording

enum class RecordingLifecycleState {
    IDLE,
    STARTING,
    RECORDING,
    STOPPING,
    STOPPED,
    FAILED,
}

enum class RecordingErrorCategory {
    NONE,
    USB,
    STORAGE,
    NTRIP,
    RECEIVER_COMMAND,
    PARSER_EXPORT,
    SERVICE_LIFECYCLE,
}

enum class RecordingErrorSeverity {
    NONE,
    INFO,
    DEGRADED,
    FATAL,
}

data class RecordingServiceState(
    val running: Boolean = false,
    val lifecycle: RecordingLifecycleState = RecordingLifecycleState.IDLE,
    val workflowLabel: String = "n/a",
    val receiverLabel: String = "n/a",
    val storageLabel: String = "n/a",
    val settingsSetLabel: String = "n/a",
    val settingsCommandProfileLabel: String = "n/a",
    val settingsBaudProfileLabel: String = "n/a",
    val settingsNtripCasterProfileLabel: String = "n/a",
    val settingsRecordingOutputProfileLabel: String = "n/a",
    val settingsStorageProfileLabel: String = "n/a",
    val sessionPath: String? = null,
    val receiverRxBytes: Long = 0,
    val txToReceiverBytes: Long = 0,
    val correctionInputBytes: Long = 0,
    val nmeaBytes: Long = 0,
    val ntripState: String = "Not configured",
    val ntripUrl: String = "n/a",
    val ntripTransferred: String = "0 B",
    val ntripRates: String = "n/a",
    val ntripStationId: String = "n/a",
    val ntripBaseLatLon: String = "n/a",
    val ggaFixQuality: Int? = null,
    val bestnavPositionType: String? = null,
    val pppStatus: String? = null,
    val latLon: String = "n/a",
    val ellipsoidalHeight: String = "n/a",
    val altitude: String = "n/a",
    val utcTime: String = "n/a",
    val latError: String = "n/a",
    val lonError: String = "n/a",
    val satellites: String = "n/a",
    val pdop: String = "n/a",
    val hdopVdop: String = "n/a",
    val horizontalAccuracy: String = "n/a",
    val verticalAccuracy: String = "n/a",
    val differentialAge: String = "n/a",
    val baseline: String = "n/a",
    val rtcmFrames: Long = 0,
    val lastError: String? = null,
    val errorCategory: RecordingErrorCategory = RecordingErrorCategory.NONE,
    val errorSeverity: RecordingErrorSeverity = RecordingErrorSeverity.NONE,
    val rawRecordingActive: Boolean = false,
    val correctionsActive: Boolean = false,
)
