package org.rtkcollector.receiver.unicore

data class Um980Telemetry(
    val source: String,
    val utcTime: String? = null,
    val solutionStatus: String? = null,
    val positionType: String? = null,
    val latDeg: Double? = null,
    val lonDeg: Double? = null,
    val altitudeM: Double? = null,
    val ellipsoidalHeightM: Double? = null,
    val latErrorM: Double? = null,
    val lonErrorM: Double? = null,
    val verticalAccuracyM: Double? = null,
    val satellitesInView: Int? = null,
    val satellitesUsed: Int? = null,
    val satellitesTracked: Int? = null,
    val gdop: Double? = null,
    val pdop: Double? = null,
    val tdop: Double? = null,
    val hdop: Double? = null,
    val vdop: Double? = null,
    val ndop: Double? = null,
    val edop: Double? = null,
    val cutoffDeg: Double? = null,
    val differentialAgeS: Double? = null,
    val solutionAgeS: Double? = null,
    val baselineLengthM: Double? = null,
    val horizontalSpeedMps: Double? = null,
    val trackDeg: Double? = null,
    val verticalSpeedMps: Double? = null,
    val stationId: String? = null,
)
